name: my composite action
description: A composite action that runs a script and checks permissions
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: |
        echo "Running script..."
        echo "Hello from my composite action!"
