name: 00-workflow-step-containers-02
on: 
    push:
jobs:
    docker_containers:
        name: docker containers
        runs-on: ubuntu-latest
        container:
             image: python:3.10
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: paths
          run: |
            echo $GITHUB_WORKSPACE    
            python --version
            ls -ltra
            pwd

        - name: Build JAR inside Docker container
          uses: docker://python:latest
          with:
            entrypoint: /bin/sh
            args: -c "python --version && ls -ltra && pwd && echo WS is $GITHUB_WORKSPACE"            

