name: 00-workflow-containers
on: [push]

jobs:
    non_docker_containers:
        name: non docker containers
        runs-on: ubuntu-latest
        steps:
        - name: paths
          run: |
            echo $GITHUB_WORKSPACE    
            python --version
            ls -ltra
            pwd
        # step 2
    docker_containers:
        name: docker containers
        runs-on: ubuntu-latest
        container:
            image: python:3.10
            volumes:
              - ${{ github.workspace }}:/app
            # use context here not $GITHUB_WORKSPACE  
        steps:
        - name: paths
          run: |
            echo $GITHUB_WORKSPACE    
            python --version
            ls -ltra
            pwd
