name: 00-custom-docker-action
on: 
    workflow_dispatch: 
jobs:
    custom_docker_action:
        name: custom docker action
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Run custom docker action
          #uses: ./.github/actions/greet-people-action
          uses: ./
          with:
            greetings: "Hello from custom action"        

        - name: Run custom docker action
          #uses: ./.github/actions/greet-people-action
          uses: vinodhdevaarul/my-actions-separate-repo@main
          with:
            name: "Vinodh Deva Arul"                    
