name: 02-composite-actions
on: 
    #push:
    workflow_dispatch: 

jobs:
    composite_action:
        name: composite action
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v3  

        - name: setup-python
          uses: ./.github/actions/setup-python
          