name: 11-github-token-privilege
on:
  push:
permissions:
  contents: write
  issues: write
  pull-requests: write


jobs:
  check-permissions:    
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check permissions
        run: |
          echo "Checking permissions..."
          echo "Contents permission: ${{ github.token.permissions.contents }}"
          echo "Issues permission: ${{ github.token.permissions.issues }}"
          echo "Pull requests permission: ${{ github.token.permissions.pull_requests }}"
     
      - name: create release
        uses: actions/create-release@v1
        with:
         tag_name: v2.0.1
         release_name: Release v2.0.1
         body: |
           This is the first release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 10     