name: 11-github-token-privilege
on:
  push:
permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  check-permissions:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check permissions
        run: |
          echo "Checking permissions..."
          echo "Contents permission: ${{ github.token.permissions.contents }}"
          echo "Issues permission: ${{ github.token.permissions.issues }}"
          echo "Pull requests permission: ${{ github.token.permissions.pull_requests }}"