name: 11-reusable-workflow
on: 
    workflow_call:
        secrets:
            PASSWORD:
                required: true
            USERPASSWORD:
                required: true
jobs:
    reusable-workflow:
        name: reusable-workflow
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: "First Hello"
          run: echo "Hello from reusable workflow"

        - name: "print secret PASSWORD"
          run: echo "${{ secrets.PASSWORD }}"

        - name: "print secret USERPASSWORD"
          run: echo "${{ secrets.USERPASSWORD }}"