name: environment approval process
on: 
    push:
jobs:
    prod-deployment:
        name: Prod Deployment
        runs-on: ubuntu-latest
        environment: 
            name: production123
        steps:
        - name: Checkout code
          uses: actions/checkout@v2     

        - name: Deploy to production
          run: echo "Deploying to production environment"

        - name: Read from environment variable  
          run: echo ${{ vars.PROD_HOSTNAME }}
          