name: environment approval process
on: 
    push:
jobs:
    prod-deployment:
        name: Prod Deployment
        runs-on: ubuntu-latest
        environment: 
            name: production
            url: https://prod.example.com
        steps:
        - name: Checkout code
          uses: actions/checkout@v2     

        - name: Deploy to production
          run: echo "Deploying to production environment"

          