name: 12-exit
on:
    push:
jobs:
    exit-job:
        runs-on: ubuntu-latest
        steps:
            - name: Run a script
              id: step-0
              run: |
                echo "Running job on ${{ matrix.os }}"
                sleep 10
                exit 0

            - name: Run a script
              if: success()
              run: |
                echo "Successful step"

            - name: Run a script
              run: |
                echo "Running job on ${{ matrix.os }}"
                sleep 10
                exit 1

            - name: Run a script
              if: failure()
              run: |
                echo "failed step"                