name: 12-exit
on:
    push:
jobs:
    exit-job:
        runs-on: ubuntu-latest
        steps:
            - name: Run a script 1
              id: step-0
              run: |
                echo "Running job 1"
                sleep 10
                exit 0

            - name: Run a script 2
              if: success()
              run: |
                echo "Successful step"

            - name: Run a script 3
              run: |
                echo "Running job 3"
                sleep 10
                exit 1

            - name: Run a script 4
              if: always() && failure()
              run: |
                echo "failed step"                