name: 12-max-parallel
on:
    push:
jobs:
    max-parallel:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                version: [1,2,3]
             max-parallel: 2
        steps:
            - name: Run a script
              run: |
                echo "Running job on ${{ matrix.os }} with version ${{ matrix.version }}"
                sleep 50