name: 22-cache-wf
on: [push]
jobs:
  cache_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip # or pipenv, poetry

      - name: find the cache dir
        run: |
          pip cache dir
    
      - name: Cache dependencies
        id: pip-cache   
        uses: actions/cache@v3
        with:
            path: |
                ~/.cache/pip
                /home/runner/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-