name: 22-cache-wf
on: [push]
jobs:
  cache_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip # or pipenv, poetry

      - name: find the cache dir 0
        run: |
          pip cache dir
    
      - name: Cache dependencies
        id: pip-cache   
        uses: actions/cache@v3
        with:
            path: |
                ~/.cache/pip
                /home/runner/.cache/pip
            key: cache-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              cache-pip-
    
      - name: Install dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          echo "steps.pip-cache.outputs.cache-hit: ${{ steps.pip-cache.outputs.cache-hit}}"
          python -m pip install -r requirements.txt
          # or pipenv install, poetry install, etc.
