name: 22-debug-commands
on: [push]
jobs:
  debug_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run debug commands
        id: step-0
        run: |
            echo "::debug::This is a debug message"
            echo "::warning::This is a warning message"
            echo "::error::This is an error message"
            echo "::notice::This is a notice message"
            echo "::group::newgroup"
            echo "This is inside a group"
            echo "::endgroup::"
            echo "::set-output name=debug_output::This is a debug output"
            echo "Debug output: ${{ steps.debug_commands.outputs.debug_output }}"
            # echo "::set-env name=DEBUG_ENV::This is a debug environment variable"
            # echo "Debug environment variable: $DEBUG_ENV"
            echo "ENV_VAR_1=Value1" >> $GITHUB_ENV
            echo "OUTPUT_VAR_1=Value2" >> $GITHUB_OUTPUT

      - name: Check debug messages
        run: |
            echo "Debug output: ${{ steps.debug_commands.outputs.debug_output }}"
            echo "Debug environment variable: $DEBUG_ENV"
            echo "1=${ENV_VAR_1}"
            echo "2=${OUTPUT_VAR_1}"
            echo "3=${{ steps.step-0.outputs.OUTPUT_VAR_1 }}"
            echo "4=${{ steps.step-0.outputs.ENV_VAR_1 }}"
            echo "5=${{ env.ENV_VAR_1 }}"
            sleep 20
  debug_commands_2:
    runs-on: ubuntu-latest
    steps:
      - name: Run debug commands
        run: |
            sleep 15
            echo "1=${ENV_VAR_1}"        
            echo "3=${{ steps.step-0.outputs.OUTPUT_VAR_1 }}"   