name: 22-dependencies
on: [push]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
         - name: create report.txt of job1
           run: |
             echo "This is a report from job1" > report.txt

         - name: upload artifact    
           uses: actions/upload-artifact@v3`
           with:
             name: my-artifact
             path: report.txt
    job2:
        runs-on: ubuntu-latest
        steps:
         - name: create report.txt of job2
           run: |
             echo "This is a report from job2" > report.txt
                
         - name: upload artifact    
           uses: actions/upload-artifact@v3
           with:
             name: my-artifact
             path: report.txt
    job3:
        runs-on: ubuntu-latest
        needs: [job1, job2]
        steps:
         - name: download artifacts from job1 and job2
           uses: actions/download-artifact@v4
           with:
             #name: my-artifact
             dependencies: job1