name: 22-debug-commands
on: [push]
jobs:
  debug_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run debug commands
        run: |
            echo "::debug::This is a debug message"
            echo "::warning::This is a warning message"
            echo "::error::This is an error message"
            echo "::notice::This is a notice message"
            echo "::group::newgroup"
            echo "This is inside a group"
            echo "::endgroup::"
            echo "::set-output name=debug_output::This is a debug output"
            echo "Debug output: ${{ steps.debug_commands.outputs.debug_output }}"
            echo "::set-env name=DEBUG_ENV::This is a debug environment variable"
            echo "Debug environment variable: $DEBUG_ENV"

      - name: Check debug messages
        run: |
            echo "Debug output: ${{ steps.debug_commands.outputs.debug_output }}"
            echo "Debug environment variable: $DEBUG_ENV"
        shell: bash            
  