name: 22-passing-values-across-jobs
on: [push]
defaults:
    run:
        shell: bash
jobs:
    job1:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        outputs:
            os: ${{ steps.step-0.outputs.os}}
            image: ${{ steps.step-1.outputs.image}}
        steps:
            - name: set os
              id: step-0
              run: echo "OS=UBUNTU" >> $GITHUB_OUTPUT
              
            - name: set image
              id: step-1
              run: echo "IMAGE=python:latest" >> $GITHUB_OUTPUT
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: get os
              run: echo "${{ needs.job1.outputs.os }}"
              
            - name: get image
              run: echo "${{ needs.job1.outputs.image }}"
              shell: bash
