name: 22-services
on: [push]
permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write
  actions: write
  checks: write
  deployments: write
  statuses: write
jobs:
    Job1:
        name: Job1
        runs-on: ubuntu-latest
        services:
            frontend-nginx:
                image: nginx:latest
                ports:
                    - 8080:80
            backend-nginx:
                image: nginx:latest
                ports:
                    - 8081:80
        steps:
            - name: Check frontend service
              run: |
                echo "Checking frontend service..."
                curl http://localhost:8080
              shell: bash                    