name: full-fledged
on:
    push:
        branches:
        - main
env:
    my_name_4: doniv     
jobs:
    build:
        name: Building Application
        runs-on: ubuntu-latest
        env:
            my_name_3: "Arul"   
        outputs:
          build_my_name_1: ${{ steps.set_my_name_2.outputs.my_name_2 }}
        steps:    
            - name: save my_name_1 in build
              run: |
                echo "::debug::processing value 1"
                echo "my_name_1=Vinodh" >> $GITHUB_ENV

            - name: save my_name_2 in build
              id: set_my_name_2
              run: |
                echo "::debug::processing value 2"
                echo "my_name_2=Deva" >> $GITHUB_OUTPUT
        
            - name: print my_name_1 in build
              run: |
                echo "$my_name_1"

            - name: print my_name_2 with env in build
              run: |
                echo ${{ env.my_name_1 }}                            

            - name: print my_name_2 with env in build
              run: |
                echo "Value is ${{ steps.set_my_name_2.outputs.my_name_2 }}"

            - name: print my_name_3 declared at Job Level
              run: |
                echo "Value is $my_name_3"                

            - name: print my_name_4 declared at Workflow Level
              run: |
                echo "Value is $my_name_4"      

            - name: write report.txt
              run: |
                echo "this is my report" >> report.txt      

            - uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: report.txt

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: print my_name_2 in deploy
          run: |
            echo "$my_name_1"
            echo "attempt 2 ${{ needs.build.outputs.build_my_name_1 }}"

        - name: print my_name_2 in deploy
          run: |
            echo "$my_name_2"            

        - name: print my_name_3 declared at Job Level
          run: |
                echo "Value is $my_name_3"        

        - name: print my_name_4 declared at Workflow Level
          run: |
                echo "Value is $my_name_4"                   

        - uses: actions/download-artifact@v4
          with:
            name: my-artifact       

        - name: cat report.txt
          run: |
                echo "::group::printing report"
                cat report.txt                  
                echo "::endgroup::"
            