name: full-fledged-sidecar
on:
  workflow_run:
    workflows: ["full-fledged"]
jobs:
    use-artifact:
        name: use-artifact
        uses: vinodhdevaarul/my-actions-repo/.github/workflows/99-full-fledged-reusable-workflow.yml@main
        with:
            name: "DonivAvedLura"
    # YOU CANNOT HAVE STEPS IN THE JOB THAT INVOKES A CALLABLE/REUSABLE WORKFLOW        
    deploy-job:
      name: deploy job
      runs-on: ubuntu-latest         
      steps:
        # - uses: actions/download-artifact@v4
        #   with:
        #     name: my-artifact       

        # - name: cat report.txt
        #   run: |
        #         echo "::group::printing report"
        #         cat report.txt                  
        #         echo "::endgroup::"

        - name: checkout code
          uses: actions/checkout@v4  


            