name: caller workflow
on:
    workflow_dispatch: 
        inputs:
            name:
                description: 'provide your name'
                default: 'some111'
                type: string
                required: true
jobs:
    called-workflow:
        uses: ./.github/workflows/reusable-wf.yml
        with:
           name: ${{ inputs.name }}                        
        secrets:
            password: ${{ secrets.PASSWORD }}
    get-date-from-called-wf:
        runs-on: ubuntu-latest
        needs: called-workflow
        steps:
            - name: printing the date from rw output
              run: echo ${{ needs.called-workflow.outputs.date_val }}