name: caller workflow
on:
    workflow_dispatch: 
        inputs:
            name:
                description: 'provide your name'
                default: 'some111'
                type: string
                required: true
jobs:
    called-workflow:
        uses: ./.github/workflows/reusable-wf.yml
        with:
           name: ${{ inputs.name }}                        