name: "debug commands"
on: [push]
jobs:
  more_on_jobs_1:
    runs-on: ubuntu-latest
    steps:
    - name: "Normal Text"
      run: echo "Normal Text"

    - name: "error Text"
      run: echo "::error::Error missing something"

    - name: "error Text 2"
      run: echo "::error title=error,file=app.js,line=2,endLine=3,col=5,endColumn=20::Missing something"

    - name: "error Text 2"
      run: echo "::debug title=debug,file=app.js,line=2,endLine=3,col=5,endColumn=20::Missing something"      

    - name: "error Text 2"
      run: echo "::notice title=notice,file=app.js,line=2,endLine=3,col=5,endColumn=20::Missing something"

    - name: "error Text 2"
      run: echo "::warning title=warning,file=app.js,line=2,endLine=3,col=5,endColumn=20::Missing something"      

    - name: "Grouping Logs"
      run: |
        echo "::group::MyGroup"      
        echo "1"      
        echo "2"      
        echo "3"      
        echo "4"      
        echo "5"      
        echo "::endgroup::"

    - name: "Secret String"
      run: echo "::add-mask::secret_string"  
    
    - name: "Secret String"
      run: echo "secret_string"  