name: dynamic matrix with inputs
on: 
    workflow_dispatch: 
        inputs:
            os:
                description:  OS Info
                default: 'ubuntu-latest,windows-latest'
                type: string
jobs:
    prepare_matrix:
        runs-on: ubuntu-latest
        outputs:
          val1: ${{steps.step-1.outputs.val1}}
          val2: ${{steps.step-2.outputs.val2}}
          val3: ${{steps.step-3.outputs.val3}}
          os_matrix: ${{steps.step-3.outputs.os_json}}
        steps:
        # transfer value between steps    
        - name: print os val
          run: echo ${{ github.event.inputs.os }}
            
        - name: echo val 1
          id: step-1
          run: echo "val1=val1" >> $GITHUB_OUTPUT

        - name: echo val 2
          id: step-2
          run: echo "val2=val2" >> $GITHUB_OUTPUT

        - name: echo val 3
          id: step-3
          run: echo "val3=val3"

        - name: print val1, val2, val3
          run: |
            echo ${{ steps.step-1.outputs.val1 }}
            echo ${{ steps.step-2.outputs.val2 }}
            echo ${{ steps.step-3.outputs.val3 }}

        - name: split inputs
          run: |
             echo "os_json=$(jq -c -R 'split(",")' <<< ${{ github.event.inputs.os }})" >> $GITHUB_OUTPUT


    dynamic_matrix_with_inputs:
        name: "Testing dynamic matrix"
        needs: prepare_matrix            
        #runs-on: ubuntu-latest
        runs-on: ${{ needs.prepare_matrix.outputs.os_matrix }}
        steps:
        # below job will not print out the value    
        - name: echo hello world
          run : echo $GITHUB_OUTPUT

        - name: print val1
          run : echo $GITHUB_OUTPUT

        - name: echo val1
          run : echo ${{ needs.prepare_matrix.outputs.val1 }}

        - name: print val2
          run : echo ${{ needs.prepare_matrix.outputs.val2 }}

        - name: print val3
          run : echo ${{ needs.prepare_matrix.outputs.val3 }}          
    