name: dynamic matrix with inputs
on: 
    push:
    workflow_dispatch: 
        inputs:
            os:
                description:  OS Info
                default: 'ubuntu-latest'
                type: string
jobs:
    prepare_matrix:
        runs-on: ubuntu-latest
        steps:
        - name: echo val 1
          id: step-1
          run: echo "val1=val1" >> $GITHUB_OUTPUT

        - name: echo val 2
          id: step-2
          run: echo "val2=val2" >> $GITHUB_OUTPUT

        - name: print val1, val2
          run: |
            echo ${{ steps.step-1.outputs.val1 }}
            echo ${{ steps.step-1.outputs.val2 }}
          

          # dynamic_matrix_with_inputs:
    #     name: "Testing dynamic matrix"            
    #     runs-on: ${{ inputs.os }}
    #     steps:
    #     - name: echo hello world
    #       run : echo "hello world"