name: Expressions & Contexts
on: [push, issues]
jobs:
  runs-on-all-events:
    runs-on: ubuntu-latest
    name: Runs all Events
    steps:
    - name: echo github contexts
      run: |
        echo ${{ toJson(github) }}

    - name: echo runner contexts
      run: |
        echo ${{ toJson(runner) }}

    - name: echo job contexts
      run: |
        echo ${{ toJson(job) }}

    - name: echo steps contexts
      run: |
        echo ${{ toJson(steps) }}

    - name: echo secrets contexts
      run: |
        echo ${{ toJson(secrets) }}                        