name: Expressions & Contexts
on: [push, issues]
jobs:
  runs-on-all-events:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: Runs all Events
    steps:
    - name: expressions
      run: |
       echo ${{ 'string' == 'String'}}  
       echo ${{ 1 > 2 }}
       echo ${{ 1 > 2 && (2 == 2) }}
       echo ${{ true == false }}

    - name: echo github contexts
      if: github.event_name == 'issues'
      run: |
        echo '${{ toJson(github) }}'

    - name: echo runner contexts
      run: |
        echo '${{ toJson(runner) }}'

    - name: echo job contexts
      run: |
        echo '${{ toJson(job) }}'

    - name: echo steps contexts
      run: |
        echo '${{ toJson(steps) }}'

    - name: echo secrets contexts
      run: |
        echo '${{ toJson(secrets) }}'                        

    - name: if 1
      if: github.ref == 'refs/heads/main'
      run: |
        echo "This is the main branch"

    - name: if 2
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "This is the main branch"

    - name: Run Tests
      id: run-tests
      run: exit 0

    - name: Upload Failure test report
      if: failure() && steps.run-tests.outcome == 'failure'
      run: echo "This step runs only if the previous step failed"

    - name: Upload Failure test report
      if: always() && steps.run-tests.outcome == 'failure'
      run: echo "This step runs only if the previous step failed"      
  