name: job-level-docker-container
on: [push]

jobs:
    job-level-docker:
        runs-on: ubuntu-latest
        container: 
            image: python:latest
        
        steps:
        - uses: actions/checkout@v4

        - name: paths
          run: |
            echo $GITHUB_WORKSPACE
            ls -ltra
            pwd

        - name: Confirm container environment
          run: |
            echo "Python version:"
            python --version
            echo
            echo "Checking for /.dockerenv:"
            ls -l /.dockerenv || echo "Not found"
            echo
            echo "/proc/1/cgroup:"
            cat /proc/1/cgroup
            echo
            echo "Container image info:"
            grep PRETTY /etc/os-release || echo "No OS info found"
            
        - run: python -m unittest discover


