name: Reusable workflow
on:
    workflow_call: 
        inputs:
            name:
                description: 'provide your name'
                default: 'someone'
                type: string
                required: true
        secrets:
            password:
                description: 'provide your password'
                required: true

jobs:
    called-workflow:
        outputs:
          date_val: ${{ steps.date-step.outputs.date_val }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: get the github context
              run: echo '${{ toJson(github) }}'

            - name: get the inputs
              run: |
                echo ${{ inputs.name }}              
                echo ${{ secrets.PASSWORD }}              

            - name: send date value
              id: date-step
              run: echo "date_val=$(date)" >> $GITHUB_OUTPUT

            - name: print date value
              run: echo "${{ steps.date-step.outputs.date_val }}            
