name: NGINX Service Example

on: [push]

jobs:
  nginx-test:
    runs-on: ubuntu-latest

    services:
      nginx_1:
        image: nginx:latest
        ports:
          - 8080:80  # Map container port 80 to host port 8080
      nginx_2:
        image: nginx:latest
        ports:
          - 8090:80  # Map container port 80 to host port 8080


    steps:
      - name: Job services context
        run: |
          echo '${{ toJson(job.services) }}'

      - name: Test NGINX response
        run: |
          curl -I http://localhost:8080
          curl -I http://localhost:8090
        shell: bash
