name: status check
run-name: status check ${{ github.event_name}}
on: [push]
jobs:
    status_check_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: run something
          run: echo "running"

        - name: exit 1
          id: fail_exit
          run: exit 1

        - name: runs on failure
          if: failure()
          run: echo "ran on failure"

        - name: runs on success
          if: success()
          run: echo "ran on success"

        - name: sleep 60
          run: sleep 60

        - name: runs on cancelled
          if: cancelled()
          run: echo "ran on cancelled"

        - name: runs on failure of step 2
          if: failure() && steps.fail_exit.conclusion == 'failure'
          run: echo "ran on failure"          

